### ISSUE TITLE
RAINBOW SIX 3 [Sles-522.88 ]do not find controler in slot 1

### ISSUE THREAD

**Issue by annahana** [jpd002/Play-#260]
System windows 10 pro
ram 4gb
gpu AMD Radeon HD 6450
cpu intel core i3 2120

if i run the emulator wit the game it says that the controler is not connected
![play ranibow six 3](https://cloud.githubusercontent.com/assets/13276505/8895347/1db95f46-33d7-11e5-8a07-dcafb879171e.PNG)

the emulator is in default setting.
other games have no problem with the controler

**Comment by drainbeam** [comment]
This issues happen with other games as wlel because there are problems with the IOP scheduling.

**Comment by jpd002** [comment]
What @drainbeam said. It's one of the things I'll be looking into pretty soon.

**Comment by jpd002** [comment]
Might be interesting to test with the latest weekly build (2015-10-11) since I've fixed some issues with controllers. I don't have that game, so, I can't test, unfortunately.

**Comment by johnnyleap** [comment]
Tried it numerous times and unfortunately it still won't detect a controller.

**Comment by jpd002** [comment]
@johnnyleap Thanks for testing, I'll get the game to do some tests myself.

**Comment by MoochMcGee** [comment]
Yu Yu Hakusho: Dark Tournament also suffers from this issue.

**Comment by annahana** [comment]
ok controler works in the game. thanks for the god work

**Comment by jpd002** [comment]
Moved here: https://github.com/jpd002/Play-Compatibility/issues/1300.
